import { Agent, PhoneNumber, CallLog } from './types'

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'Customer Support Bot',
    systemPrompt: 'You are a helpful customer support representative. Answer questions about our products and services in a friendly manner.',
    firstMessage: 'Hello! How can I help you today?',
    voice: {
      provider: 'eleven-labs',
      voiceId: 'EXAVITQu4vr4xnSDxMaL',
    },
    llm: {
      provider: 'openai',
      model: 'gpt-4-turbo',
    },
    temperature: 0.7,
    maxDuration: 600,
    status: 'active',
    createdAt: new Date('2024-01-15'),
    callsCount: 1250,
    totalMinutes: 8750,
  },
  {
    id: '2',
    name: 'Sales Assistant',
    systemPrompt: 'You are an enthusiastic sales representative. Help customers find the right products for their needs.',
    firstMessage: 'Hi there! Welcome! What can I help you find today?',
    voice: {
      provider: 'google',
      voiceId: 'en-US-Neural2-C',
    },
    llm: {
      provider: 'openai',
      model: 'gpt-4-turbo',
    },
    temperature: 0.8,
    maxDuration: 300,
    status: 'active',
    createdAt: new Date('2024-02-01'),
    callsCount: 856,
    totalMinutes: 5120,
  },
  {
    id: '3',
    name: 'Appointment Scheduler',
    systemPrompt: 'Help customers book appointments. Be efficient and clear about available time slots.',
    firstMessage: 'Good day! I can help you schedule an appointment. What date works best for you?',
    voice: {
      provider: 'azure',
      voiceId: 'en-US-AriaNeural',
    },
    llm: {
      provider: 'groq',
      model: 'mixtral-8x7b-32768',
    },
    temperature: 0.5,
    maxDuration: 900,
    status: 'inactive',
    createdAt: new Date('2024-03-10'),
    callsCount: 345,
    totalMinutes: 2890,
  },
  {
    id: '4',
    name: 'Technical Support',
    systemPrompt: 'You are a technical support specialist. Help troubleshoot issues and provide clear solutions.',
    firstMessage: 'Welcome to technical support. Can you describe the issue you are experiencing?',
    voice: {
      provider: 'eleven-labs',
      voiceId: 'TxGEqnHWrfWFTLV8z5gx',
    },
    llm: {
      provider: 'gemini',
      model: 'gemini-1.5-pro',
    },
    temperature: 0.6,
    maxDuration: 1200,
    status: 'active',
    createdAt: new Date('2024-01-20'),
    callsCount: 2100,
    totalMinutes: 15780,
  },
  {
    id: '5',
    name: 'Feedback Collector',
    systemPrompt: 'Politely ask customers for feedback about their recent experience. Be appreciative and professional.',
    firstMessage: 'Hi! We would love to hear about your experience. Do you have a few minutes?',
    voice: {
      provider: 'google',
      voiceId: 'en-US-Neural2-A',
    },
    llm: {
      provider: 'openai',
      model: 'gpt-4-turbo',
    },
    temperature: 0.6,
    maxDuration: 600,
    status: 'active',
    createdAt: new Date('2024-02-28'),
    callsCount: 567,
    totalMinutes: 3456,
  },
]

export const mockPhoneNumbers: PhoneNumber[] = [
  {
    id: '1',
    number: '+1 (555) 123-4567',
    country: 'United States',
    type: 'local',
    assignedAgent: {
      id: '1',
      name: 'Customer Support Bot',
    },
    status: 'active',
    monthlyCost: 1000,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    number: '+1 (800) 555-0123',
    country: 'United States',
    type: 'toll-free',
    assignedAgent: {
      id: '2',
      name: 'Sales Assistant',
    },
    status: 'active',
    monthlyCost: 1500,
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '3',
    number: '+44 20 7946 0958',
    country: 'United Kingdom',
    type: 'local',
    status: 'inactive',
    monthlyCost: 1200,
    createdAt: new Date('2024-02-05'),
  },
  {
    id: '4',
    number: '+1 (202) 555-0173',
    country: 'United States',
    type: 'local',
    assignedAgent: {
      id: '4',
      name: 'Technical Support',
    },
    status: 'active',
    monthlyCost: 1000,
    createdAt: new Date('2024-03-01'),
  },
]

export const mockCallLogs: CallLog[] = [
  {
    id: '1',
    agentId: '1',
    agentName: 'Customer Support Bot',
    fromNumber: '+1 (555) 987-6543',
    toNumber: '+1 (555) 123-4567',
    direction: 'inbound',
    duration: 234,
    status: 'completed',
    startTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 234 * 1000),
    costCents: 58,
    transcript: 'Customer: Hi, I have a question about my account. Agent: Of course! How can I help?',
  },
  {
    id: '2',
    agentId: '2',
    agentName: 'Sales Assistant',
    fromNumber: '+1 (555) 654-3210',
    toNumber: '+1 (800) 555-0123',
    direction: 'inbound',
    duration: 456,
    status: 'completed',
    startTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 456 * 1000),
    costCents: 114,
    recordingUrl: '#',
  },
  {
    id: '3',
    agentId: '4',
    agentName: 'Technical Support',
    fromNumber: '+1 (555) 321-0987',
    toNumber: '+1 (202) 555-0173',
    direction: 'inbound',
    duration: 678,
    status: 'completed',
    startTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 678 * 1000),
    costCents: 169,
  },
  {
    id: '4',
    agentId: '1',
    agentName: 'Customer Support Bot',
    fromNumber: '+1 (555) 432-1098',
    toNumber: '+1 (555) 123-4567',
    direction: 'inbound',
    duration: 120,
    status: 'failed',
    startTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 120 * 1000),
    costCents: 30,
  },
  {
    id: '5',
    agentId: '5',
    agentName: 'Feedback Collector',
    fromNumber: '+1 (555) 789-0123',
    toNumber: '+1 (555) 123-4567',
    direction: 'outbound',
    duration: 180,
    status: 'completed',
    startTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 180 * 1000),
    costCents: 45,
  },
]
